/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package sga.web.form;

import org.apache.struts.validator.ValidatorActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-15-2010
 * 
 * XDoclet definition:
 * @struts.form name="personaForm"
 */
//ValidatorActionForm para validacion automatica cone l plugin
public class PersonaForm extends ValidatorActionForm {
	/*
	 * Generated fields
	 */

	/** apellido property */
	private String apellido;

	/** nombre property */
	private String nombre;
	
	/** nombre property */
	private Integer idPersona;
	

	/*
	 * Generated Methods
	 */

	public Integer getIdPersona() {
		return idPersona;
	}

	public void setIdPersona(Integer idPersona) {
		this.idPersona = idPersona;
	}

	/** 
	 * Returns the apellido.
	 * @return String
	 */
	public String getApellido() {
		return apellido;
	}

	/** 
	 * Set the apellido.
	 * @param apellido The apellido to set
	 */
	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	/** 
	 * Returns the nombre.
	 * @return String
	 */
	public String getNombre() {
		return nombre;
	}

	/** 
	 * Set the nombre.
	 * @param nombre The nombre to set
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}